export { default as Button } from './button/Button';
export { default as InfoItem } from './info-item/InfoItem';
export { default as Input } from './input/Input';
export { default as NavBarItem } from './navbar-item/NavBarItem';
export { default as ProfilePhoto } from './profile-photo/ProfilePhoto';
export { default as BackgroundPhoto } from './background-photo/BackgroundPhoto';
export { default as Table } from './table/Table';
export { default as Wrapper } from './wrapper/Wrapper';
//export { default as StagiaireCard } from './stagiaire-card/StagiaireCard';